### ISSUE TITLE
unescaped characters in regexp

### ISSUE THREAD

**Issue by alpha-er** [concourse/s3-resource#104]
When regexp param has unescaped characters, e.g.
```
- name: javascript-file
    type: s3
    source:
      bucket: releases
      regexp: my.website.com/scripts/my-javascript-(.*).js
      access_key_id: ((aws_id))
      secret_access_key: ((aws_key))
      region_name: ((aws_region))
```
It fails the resource check with:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31merror listing files: SerializationError: failed to decode REST XML response
caused by: XML syntax error on line 2: illegal character code U+0010
[0m
```
But when the chars are escaped in regexp param, i.e.
```
regexp: my\.website\.com/scripts/my-javascript-(.*)\.js
```
It fails the `put` step with:
```
error running command: AccessDenied: Access Denied
	status code: 403
```

Anybody else came across with this problem and if there's a workaround?
