### ISSUE TITLE
Support 'unpack' when initial_content_binary is an archive file

### ISSUE THREAD

**Issue by grenzr** [concourse/s3-resource#116]
Hi all, we have an s3 input as follows:

```
- name: bbl-state
  type: s3
  source:
    <<: *minio-s3
    bucket: bosh-state-files
    regexp: bbl-state-(.*).tgz
    initial_path: /bbl-state-0.0.0.tgz
    initial_content_binary: ((bbl-state-init-tgz))
```

And when the resource is used we do so as follows:

```
    - get: bbl-state
      params:
        unpack: true
```

However, I have just noticed that the first execution does not unpack the initial_content_binary. As I can see in the code, it attempts to extract before placing the initial binary.

Would you accept a PR to resolve this, or was this by design for some reason?
