### ISSUE TITLE
unable to use version to pin s3 resource

### ISSUE THREAD

**Issue by linusguan** [concourse/s3-resource#118]
Context:
I am defining two jobs with one to build and the other to deploy. 
I use semvar to track version and use it to name the artifact like artifact-0.0.1.zip, artifact-0.0.2.zip and store them on S3.
When deploy job is run I get version from semvar resource and want to get the artifact matching the version.

According to the readme file, I can use `version`:
> `version`: The version identified in the file name.
so I should be able to do something like:
```
  - name: deploy  
    plan:
      - get: version
        passed: 
          - build
        trigger: true
      - get: artifact
        version: 
          version-number: version/number
```
But I don't see a way to do that, could anyone please help explain if there is a way to achieve this?
I think it should be an expected behavior and ideal use case.
Thanks!
