### ISSUE TITLE
Support tags

### ISSUE THREAD

**Issue by fiftin** [concourse/s3-resource#119]
It would be useful to display tags in metainfo of S3 resource and have ability to read/put tags to/from JSON-file.
```yml
- put: release
  params:
    file: path/to/release-*.tgz
    tags_file: path/to/tags-*.json
```

and

```yml
- get: release
  params:
     tags_file: tags.json
```

This would allow for example to put info about commit in the tags.
