### ISSUE TITLE
Where does the downloaded S3 object go?

### ISSUE THREAD

**Issue by christopher-wong** [concourse/s3-resource#127]
When I look for the download object in a linux container task attached to the job, I don't see the object. Am I looking in the wrong place?

```yaml
- name: manifest-bundle
    type: s3
    source:
      bucket: eks-manifests
      regexp: my-application/(.*).tar.gz
      region_name: us-west-1
      access_key_id: ((aws_access_key_id))
      secret_access_key: ((aws_secrey_access_key))
      unpack: true
```

```
jobs:
  - name: deploy-dev
    plan:
      - get: manifest-bundle
      - task: deploy-dev
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: <my_linux_image>
              aws_access_key_id: ((aws_access_key_id))
              aws_secrey_access_key: ((aws_secrey_access_key))
              tag: latest
          run:
            path: /bin/sh
            args:
            - -c
            - |
              ls -al
```
