### ISSUE TITLE
S3 Resource get stuck

### ISSUE THREAD

**Issue by demchris** [concourse/s3-resource#130]
Hi,

We currently have an issue with s3 resource we're looking at to be triggered. For some reason, when I try to manually trigger my job, my job get stuck at retrieving my s3 resource and nothing append.

I created a simple pipeline to reproduce the problem.

Here is what I see in my dashboard :

![image](https://user-images.githubusercontent.com/1652717/60739354-9c88c880-9f2f-11e9-8bf4-d2d978b9e94b.png)

Here is my bucket content, as you can see, I have 2 versions of the observed file (openam-server-6.5.0.2.war and openam-server-6.5.1.war, normally, I should get the openam-server-6.5.1.war as new version: 

![image](https://user-images.githubusercontent.com/1652717/60739402-cc37d080-9f2f-11e9-802c-d861ad471d69.png)

And finally, here is my sample pipeline that reproduces the problem.

```
resources:
- name: openam-server
  type: s3
  source:
    region_name: ca-central-1
    bucket: builds.idstacks.io
    regexp: /forgerock/openam-server-(.*).war
    access_key_id: ((aws.access-key-id))
    secret_access_key: ((aws.secret-access-key))
    skip_download: true

jobs:
- name: get-version
  serial_groups: [version]
  plan:
    - get: openam-server
      trigger: true
    - task: get-version
      config:
        platform: linux

        image_resource:
          type: docker-image
          source:
            repository: alpine

        inputs:
          - name: openam-server
        outputs:
          - name: build-output
        run:
          path: cat
          args: [openam-server/version]
```
