### ISSUE TITLE
Gracefully handle differences in s3 API support

### ISSUE THREAD

**Issue by kallisti5** [concourse/s3-resource#133]
we're using Wasabi for our s3 bucket storage, and this resource fails to properly connect due to assumptions about supporting the versioning api.

```
checking failed
resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31merror finding versions: NotImplemented: A header you provided implies functionality that is not implemented
	status code: 501, request id: , host id: 
[0m
```

**Comment by kallisti5** [comment]
The same applies if the server supports versioning, but it is disabled:
```
stderr:
[31merror finding versions: bucket is not versioned
[0m
```

**Comment by kallisti5** [comment]
Another error attempting to upload to wasabi:
```
error running command: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, HeadObjectInput.Key.
```

```yaml
resources:
  - name: upload-image
    type: s3
    source:
      bucket: haiku-((profile))-test
      access_key_id: ((s3key))
      secret_access_key: ((s3secret))
      endpoint: ((s3endpoint))
jobs:
  - name: blah
    plan:
    .
    .
      - put: upload-image
        params:
          file: artifacts.((arch))/*.zip
```
