### ISSUE TITLE
Uploading file hangs when using Minio

### ISSUE THREAD

**Issue by goldginkgo** [concourse/s3-resource#135]
The uploading process never ends when I put a file to Minio. But the file is updated in Minio according to the updated time. Here is the output in Concourse.
```
2.58 MB / 2.58 MB [=====================================] 100.00 % 12.64 MB/s 0s
```
However, when I try to upload a text file of several  just several KB, it works fine and the task can be completed.

I deployed Concourse and Minio using docker compose(https://github.com/concourse/concourse-docker).
```
version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse:5.4.1
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse:5.4.1
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - "80:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_HTTP_TRACE: /tmp/minio.log
    command: server /data
```
The following pipeline was used to do the test. I created a bucket called test in Minio and uploaded bootstrap (https://github.com/twbs/bootstrap/archive/v4.3.1.zip) to the bucket before executing the pipeline.
```
resources:
- name: release
  type: s3
  source:
    endpoint: http://192.168.1.109
    bucket: test
    regexp: bootstrap-(.*).zip
    access_key_id: minio
    secret_access_key: minio123
    disable_ssl: true

jobs:
- name: download-file
  plan:
  - get: release
  - put: release
    params:
      file: release/bootstrap-*.zip

```
Any idea on what's causing the issue?
