### ISSUE TITLE
Keep archive even with unpack

### ISSUE THREAD

**Issue by tenjaa** [concourse/s3-resource#136]
Hey,
we are using a versioned s3 bucket to store zipped artifacts that should be deployed later.
First of all we have an `artifact-SNAPSHOT.tar.gz`. In case some tests pass we promote this to a "deployable" artifact as `artifact.tar.gz`.
It would make it a bit easier and also avoids redownloading the artifact if we can just keep the archive next to the extracted files.
Or do you have a completly different idea how to solve this?

We do this in one job that looks basically like that:
```yaml
- name: test
  plan:
  - get: snapshot
    params:
      unpack: true
  - put: push-snapshot
    resource: cf-cli
    params:
      command: push
      manifest: snapshot/e2e/manifest.yml
      path: snapshot/e2e/app
  - task: run-some-tests
  - get: snapshot-to-promote
    resource: snapshot
  - put: artifact
    params:
      file: snapshot-to-promote/artifact-SNAPSHOT.tar.gz
```
