### ISSUE TITLE
404 on get after successful check

### ISSUE THREAD

**Issue by schmurfy** [concourse/s3-resource#144]
I am doing some tests with minio, here is the content of the bucket:

```
changed-files
  0
    service1
    service2
```

And here is the pipeline I am using:

```

resources:
  - name: "changed-files"
    type: "s3"
    source:
      bucket: "changed-files"
      regexp: "(?P<version>.+/.+)/"
      endpoint: "http://minio.service.consul:9000"
      cloudfront_url: "http://minio.service.consul:9000"
      disable_ssl: true
      access_key_id: "..."
      secret_access_key: "..."

jobs:
  - name: "act on changes"
    plan:
      - { get: "changed-files", trigger: true }
      - task: "print-changed"
        config:
          platform: "linux"
          inputs:
            - { name: "changed-files" }
          image_resource:
            type: "registry-image"
            source: { repository: alpine }
          
          run:
            path: sh
            dir: changed-files
            args:
              - -ec
              - |
                echo "TRIGGERED"
```

The resource check correctly finds two new versions: `0/service1` and `0/service2` but when the job executes the get resource send these requests to my minio server for some reasons:

```
HEAD /0/service1
HEAD /0/service2
```

of course the server returns a 404 since the bucket name is missing, I did some tests but I am at a loss as to why it forgets to include the bucket name in the requested path.

I am running the latest minio release which is `2020-05-08T02:40:49Z`
