### ISSUE TITLE
Code sample

### ISSUE THREAD

**Issue by SagarDamu** [concourse/s3-resource#159]
Hi,
 As I'm new to the concourse, now there is a scenario where I need to upload the file to the s3 bucket and pick a particular value from that file which is uploaded previously and use it in another job, if there is any sample code or syntax for uploading and downloading the file from s3 bucket through concourse it will be helpful, please provide if any sample code or syntax available. Thanks in advance.

**Comment by taylorsilva** [comment]
Unclear what the question is. Sounds like you're asking how to pass the uploaded artifact from one job to the next. Quick example of that would be:

```yaml
resources:
- name: some-object
  type: s3
  source:
    bucket: my-bucket
    versioned_file: my-file

jobs:
- name: job-a
  plan:
    - task: generate-file
      config:
        platform: linux
        # omitting the rest, but let's pretend this task
        # creates an output called "date" which contains
        # the date in a file called "now"
    - put: some-objects
      params:
        file: date/now

- name: job-b
  plan:
    - get: some-object
      passed: [job-a] #this is how we pass the artifact from one job to the next
```
