### ISSUE TITLE
Seeing `panic` in `s3client.go` with version 2.0.0

### ISSUE THREAD

**Issue by aramprice** [concourse/s3-resource#178]
### Describe the bug

This is possibly because we are using Role ARN in our pipeline.

The output we see from the resource is:
```
selected worker: 11fd09ed-2064-4dee-8ebf-207eca56d5cb
269 B / 269 B [--------------------------------------------------] 100.00% ? p/spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb3dd16]

goroutine 1 [running]:
github.com/concourse/s3-resource.(*s3client).URL(0x0?, {0xc00019e960, 0x13}, {0xc00018b640, 0x1d}, 0xe?, {0x0?, 0x16?})
	github.com/concourse/s3-resource/s3client.go:429 +0x356
github.com/concourse/s3-resource/in.(*Command).getURL(_, {{{0xc00019e948, 0x14}, {0xc00018cc30, 0x28}, {0x0, 0x0}, {0xc00018cba0, 0x30}, {0xc00019e960, ...}, ...}, ...}, ...)
	github.com/concourse/s3-resource/in/command.go:232 +0x58
github.com/concourse/s3-resource/in.(*Command).Run(_, {_, _}, {{{0xc00019e948, 0x14}, {0xc00018cc30, 0x28}, {0x0, 0x0}, {0xc00018cba0, ...}, ...}, ...})
	github.com/concourse/s3-resource/in/command.go:135 +0xb46
main.main()
	github.com/concourse/s3-resource/cmd/in/main.go:69 +0x491
```

Our configuration is:
```yaml
- name: build-number-version
  type: s3
  source:
    bucket: sum-bukit
    region_name: us-west-1
    access_key_id: ((aws-assume-artifacts.username))
    secret_access_key: ((aws-assume-artifacts.password))
    aws_role_arn: ((aws-assume-artifacts.role_arn))
    regexp: builds/<%= major_minor %>.(\d+-build\.\d+)\.json
```

### Reproduction steps

In our concourse the `get` consistently fails with the `panic` noted above.

when we intercept the container we see that the JSON file _has_ been downloaded to disk.

### Expected behavior

No `panic` in the ~disco~ resource.
