### ISSUE TITLE
`put` should upload to the directory specified in `regexp`

### ISSUE THREAD

**Issue by vito** [concourse/s3-resource#19]
Today you have to specify `regexp: path/to/foo-(.*).tgz`, which is fine and all for checking, but gets awkward when you want to upload a file to `path/to`. The only way to do that currently us via using `from` and `to`, which is deprecated and a bit confusing in how it works.

Instead, the file specified should be uploaded to whatever parent directory is specified in the `regexp`.

Full usage example:

```
resources:
- name: foo
  type: s3
  source:
    bucket: my-bucket
    regexp: path/to/foo-(.*).tgz

jobs:
- name: upload-foo
  plan:
  - task: make-foo
    # ...
  - put: foo
    params: {file: made-foo/foo-*.tgz}
```
