### ISSUE TITLE
Feature Request: IAM instance profile support

### ISSUE THREAD

**Issue by keymon** [concourse/s3-resource#20]
If concourse is running on AWS, it can take advantage of IAM instance profiles to access the S3 buckets.

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html

It can be enabled if, for instance, the credentials are empty or if with an additional option `credentials_source`, like:

```
  - name: myfile.txt
    type: s3
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      versioned_file: myfile.txt
      credentials_source: env_or_profile
```
