### ISSUE TITLE
How to use minio as s3 endpoint

### ISSUE THREAD

**Issue by baszalmstra** [concourse/s3-resource#35]
I'm using concourse 1.3.0-rc.73, I'm trying to use Minio (https://github.com/minio/minio) as a compatible s3 endpoint but when I use a configuration like this:

```
- name: release_candidate
  type: s3
  source:
    bucket: artifacts
    regexp: dev-(.*).tgz
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: http://192.168.1.128:9000
    cloudfront_url: http://192.168.1.128:9000
```

I get this error:

```
error: check failed with exit status '1':
error checking for new versions: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
        status code: 403, request id: 8220B4E973DE1AC9
```

It seems the service is still targeting AWS. Is it possible to use Minio and if so, what are the proper parameters to use?

Thanks!
