### ISSUE TITLE
Generating signed URLs should be done via `put`

### ISSUE THREAD

**Issue by vito** [concourse/s3-resource#53]
Related to https://github.com/concourse/concourse/issues/622 and https://github.com/concourse/s3-resource/issues/47

`private: true` on `get` is confusingly named and breaks resource semantics, because the URL it provides has an expiration value, and is different every time it's generated, making `get` nondeterministic.

Generating the URL should instead be generated by a `put`, guaranteeing that it'll be a new URL each time. This could look like:

```yaml
- get: my-bucket-thing
- put: my-bucket-thing
  params: {sign: my-bucket-thing, expires_in: 24h}
```

The put would yield a version like `{path: foo, signed_at: <timestamp>}` (or `version_id` if using `versioned_file`). The `get` resulting from the `put` would generate the signed URL. This fixes the hole because the `get` will be generating a URL valid for that particular timestamp (because it's the start of the expiration countdown), and the timestamp will be different every time.
