### ISSUE TITLE
Get specific version of file from s3

### ISSUE THREAD

**Issue by msarahan** [concourse/s3-resource#59]
I would like to request a specific version from S3.  My jobs on one test server never start, and on the other, they get the newest version of that tarball, rather than the specified one

I have my resource like this:

```
- name: s3-archive
  source:
    access_key_id: <key>
    bucket: <bucket>
    regexp: recipes-(.*).tar.bz2
    secret_access_key: <secret-key>
```

and my get section like: 

```
  - get: s3-archive
    params:
      version: 1.0.0
    passed: []
    trigger: true
```

The output in the web UI is:

```
discovering any new versions of s3-archive
waiting for a suitable set of input versions
s3-archive - no versions available
```

However, I can see from the AWS console that I do have matching patterns available.

I have tried removing the ```trigger: true``` part, but no change.  

Is this expected behavior?  Is it not possible to specify a particular version to get?
