### ISSUE TITLE
Getting resource fails when regex is changed

### ISSUE THREAD

**Issue by evanshort73** [concourse/s3-resource#7]
If you deploy the resource with something like

```
- name: artifact
  type: s3
  source:
    ...
    regexp: blah-(\d+)\.tar
```

and suddenly you add compression (gzip) to your tars, so you change the resource to

```
- name: artifact
  type: s3
  source:
    ...
    regexp: blah-(\d+)\.tar\.gz
```

If a previous version of the resource has already been fetched (the uncompressed version, e.g. version 1337), then after a fly configure, getting new versions of the resource fails with an error:

```
checking failed
---
resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31merror running command: version number could not be found in: blah-1337.tar
[0m




path blah-1337.tar
```
