### ISSUE TITLE
error running command: InvalidParameter: 1 validation error(s) found.

### ISSUE THREAD

**Issue by phynias** [concourse/s3-resource#93]
I can not get an upload to work at all.
I get:

> error running command: InvalidParameter: 1 validation error(s) found.
> - minimum field size of 1, HeadObjectInput.Key.

```
- name: release-s3
  type: s3
  source:
    bucket: dev
    region_name: us-west-1
    regex: deployment/vdoengine_static_v(.*).zip
    access_key_id: XXX
    secret_access_key: XXXXX

  - put: release-s3
    params:
      file: built-vdoengine/vdoengine_static_v*.zip
```

Am missing something?
