### ISSUE TITLE
[trigger] Add an option to not download the s3 file

### ISSUE THREAD

**Issue by talset** [concourse/s3-resource#95]
Here is my usecase :

I build an application and put the file on s3
```
    - put: s3-release
      params:
        acl: private
        file: release/release.tar.gz
```

A second task is trigger by the get
```
    - get: s3-release
      trigger: true
      passed:
        - build-release
```

This task just need to know if the file have been change (we dont need to download it on concourse)

The issue is when we use get the file is downloaded

`967.73 MB / 967.73 MB [================================] 100.00 % 108.67 MB/s 8s`

Is there a way to have a parameter `skip_download` like docker-image-resource in order to just use s3 as a trigger ?
