### ISSUE TITLE
Put task to an S3 bucket fails even though the actual upload succeeded

### ISSUE THREAD

**Issue by jyriok** [concourse/s3-resource#98]
Hello,

i use S3 compatible storage versioned  for store my bbr backup.

so i use this :

```
- name: AF-storage
  type: s3
  source:
    bucket: ee.cloud-backup
    endpoint: 10.x.x.10:8080
    disable_ssl: true
    use_v2_signing: true
    versioned_file: backup/cf-backup.tar
    access_key_id: SOMESECRETSOMESECRET
    secret_access_key: SOMESECRETSOMESECRET
```

and job :
```
  - put: AF-storage
    params:
      file: backup/cf-backup.tar
```

and when my pipeline is done and concourse push the file on S3, i've this error message :

`3.48 MB / 3.48 MB [=====================================] 100.00 % 16.59 MB/s 0serror running command: object versioning not enabled`

but my file is rightly stored and versioned on my bucket !

![image](https://user-images.githubusercontent.com/1574064/38799655-5d46c772-4165-11e8-9a48-3f6d22d03800.png)

what's i'm doing wrong ? :o

thanks !
